# Generated by Django 3.0.2 on 2020-01-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunneberg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='img_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
