# Generated by Django 3.0.2 on 2020-01-17 12:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunneberg', '0002_site_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='img_cows',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
