# Generated by Django 3.0.2 on 2020-01-20 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sunneberg', '0003_auto_20200117_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='img_cows',
        ),
        migrations.AddField(
            model_name='site',
            name='img_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='C:\\Users\\TAASIBA2\\Documents\\Pypy\\Sunneberg\\sunneberg/media'),
            preserve_default=False,
        ),
    ]
