# Generated by Django 3.0.2 on 2020-02-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunneberg', '0004_auto_20200120_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(blank=True, max_length=200)),
                ('img_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
