# Generated by Django 3.0.2 on 2020-02-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunneberg', '0005_auto_20200211_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_name', models.CharField(blank=True, max_length=200)),
                ('txt_title', models.CharField(blank=True, max_length=200)),
                ('txt_text', models.CharField(blank=True, max_length=4000)),
            ],
        ),
    ]
