# Generated by Django 3.0.2 on 2020-02-13 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunneberg', '0006_sitetext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200)),
                ('list_content', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), size=None), size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='sitetext',
            name='txt_text',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
