# Generated by Django 3.0.2 on 2020-02-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunneberg', '0007_auto_20200213_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='')),
            ],
        ),
    ]
