# Generated by Django 3.0.2 on 2020-02-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunneberg', '0008_pdfmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmodel',
            name='pdf_title',
            field=models.TextField(blank=True),
        ),
    ]
