language: python
python:
  - "3.6"      # current default Python on Travis CI

# safelist
branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="sunneberg-project.settings"

services:
  - postgresql

script:
  - ./manage.py test