language: python
python:
  - "3.6"      # current default Python on Travis CI

# safelist
branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres

#env: DJANGO_SETTINGS_MODULE="sunneberg_project.settings.travis"


services:
  - postgresql

script:
  - python ./manage.py test